name: Sync Ecologi data

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  keep_file_updated:
    runs-on: ubuntu-latest
    name: Keep file updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v4
    - name: Update file
      id: update_file
      uses: neilstudd/keep-remote-file-locally-up-to-date-action@main
      with:
        url: https://public.ecologi.com/users/neilstudd/impact
        file_in_repo: _data/ecologi.json
        git_user: neilstudd
        git_email: github@neilstudd.com
